[package]
name = "monotone-frameworks-rs"
version = "0.1.0"
authors = ["lihram"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
