name: Rust

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: rust-toolchain
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: nightly
    - uses: actions/checkout@v2
    - name: Build
      uses: actions-rs/cargo@v1.0.1
      with:
        toolchain: nightly
        command: build
        args: --verbose
    - name: Test
      uses: actions-rs/cargo@v1.0.1
      with:
        toolchain: nightly
        command: test
        args: --verbose
    - name: rust-tarpaulin
      uses: actions-rs/tarpaulin@v0.1.0
      with:
        toolchain: nightly

